import { ThemeDefinition } from './types';

export const themes: Record<string, ThemeDefinition> = {
  dark: {
    id: 'dark',
    name: 'Dark',
    colors: {
      bgMain: '#1e1e1e',
      bgSidebar: '#252526',
      bgEditor: '#1e1e1e',
      bgCanvas: '#2d2d2d',
      bgToolbar: '#333333',
      bgStatusBar: '#007acc',
      bgTitlebar: '#3c3c3c',
      bgPanel: '#252526',
      bgInput: '#3c3c3c',
      bgDropdown: '#252526',
      bgButton: '#3c3c3c',
      bgButtonHover: '#4a4a4a',
      bgActive: '#094771',
      bgHover: '#2a2d2e',
      textPrimary: '#cccccc',
      textSecondary: '#999999',
      textMuted: '#666666',
      textInverse: '#ffffff',
      borderColor: '#3c3c3c',
      borderFocus: '#007acc',
      accentPrimary: '#007acc',
      accentSecondary: '#e94560',
      accentSuccess: '#4ec9b0',
      accentWarning: '#dcdcaa',
      accentError: '#f44747',
      monacoTheme: 'vs-dark',
    },
  },

  light: {
    id: 'light',
    name: 'Light',
    colors: {
      bgMain: '#ffffff',
      bgSidebar: '#f3f3f3',
      bgEditor: '#ffffff',
      bgCanvas: '#fafafa',
      bgToolbar: '#e8e8e8',
      bgStatusBar: '#007acc',
      bgTitlebar: '#dddddd',
      bgPanel: '#f3f3f3',
      bgInput: '#ffffff',
      bgDropdown: '#ffffff',
      bgButton: '#e8e8e8',
      bgButtonHover: '#d0d0d0',
      bgActive: '#e4e6f1',
      bgHover: '#e8e8e8',
      textPrimary: '#333333',
      textSecondary: '#666666',
      textMuted: '#999999',
      textInverse: '#ffffff',
      borderColor: '#d4d4d4',
      borderFocus: '#007acc',
      accentPrimary: '#007acc',
      accentSecondary: '#e94560',
      accentSuccess: '#4ec9b0',
      accentWarning: '#e5a100',
      accentError: '#f44747',
      monacoTheme: 'vs',
    },
  },

  custom: {
    id: 'custom',
    name: 'Midnight Blue',
    colors: {
      bgMain: '#0d1117',
      bgSidebar: '#161b22',
      bgEditor: '#0d1117',
      bgCanvas: '#1a2332',
      bgToolbar: '#21262d',
      bgStatusBar: '#58a6ff',
      bgTitlebar: '#161b22',
      bgPanel: '#161b22',
      bgInput: '#21262d',
      bgDropdown: '#161b22',
      bgButton: '#21262d',
      bgButtonHover: '#30363d',
      bgActive: '#1f6feb',
      bgHover: '#1c2128',
      textPrimary: '#c9d1d9',
      textSecondary: '#8b949e',
      textMuted: '#484f58',
      textInverse: '#ffffff',
      borderColor: '#30363d',
      borderFocus: '#58a6ff',
      accentPrimary: '#58a6ff',
      accentSecondary: '#f78166',
      accentSuccess: '#3fb950',
      accentWarning: '#d2991d',
      accentError: '#f85149',
      monacoTheme: 'vs-dark',
    },
  },
};

export type ThemeId = keyof typeof themes;
export const DEFAULT_THEME: ThemeId = 'dark';
